const ALLOWED_ORIGIN = "https://q9999499-collab.github.io";

const GEMINI_MODEL = "gemini-3.6-flash";
const GEMINI_IMAGE_MODEL = "gemini-3.1-flash-image";
const GROQ_MODEL = "llama-3.3-70b-versatile";
const FLUX_FAST_MODEL = "@cf/black-forest-labs/flux-2-klein-4b";
const FLUX_QUALITY_MODEL = "@cf/black-forest-labs/flux-2-dev";
const CORS = {"Access-Control-Allow-Origin": ALLOWED_ORIGIN,"Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Qasim-Client","Access-Control-Max-Age":"86400",Vary:"Origin"};
const SYSTEM_PROMPT=`You are Qasim Mind. Answer naturally, accurately, helpfully and completely. Support English, Urdu, Roman Urdu and mixed language; follow the user's language. Match the requested length. For complex questions, use clear headings, bullets, steps, examples, calculations or tables when useful. Never return an empty answer. Do not claim an image, file, web search or tool was used unless it actually was.`;
function json(data,status=200,extraHeaders={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...CORS,...extraHeaders}})}
function clean(value){return typeof value==="string"?value.replace(/\u0000/g,"").trim():""}
function clampInt(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.floor(n))):fallback}
async function readJSON(request){try{return await request.json()}catch{return null}}
async function timeoutFetch(url,options={},timeout=50000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
function normalizeMessages(messages){if(!Array.isArray(messages))return [];return messages.filter(m=>m&&(m.role==="user"||m.role==="assistant")&&typeof m.content==="string").map(m=>({role:m.role,content:clean(m.content)})).filter(m=>m.content).slice(-20)}
function extractGeminiText(data){const parts=data?.candidates?.[0]?.content?.parts;if(!Array.isArray(parts))return "";return parts.map(p=>typeof p?.text==="string"?p.text:"").join("").trim()}
async function groq(messages,env,maxTokens){if(!env.GROQ_API_KEY)throw new Error("GROQ_API_KEY is not configured");const r=await timeoutFetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.GROQ_API_KEY}`},body:JSON.stringify({model:GROQ_MODEL,messages:[{role:"system",content:SYSTEM_PROMPT},...messages],temperature:.3,max_tokens:Math.min(maxTokens,32768)})},50000);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error?.message||`Groq HTTP ${r.status}`);const a=clean(d?.choices?.[0]?.message?.content);if(!a)throw new Error("Groq returned an empty response");return a}
async function gemini(messages,env,maxTokens){if(!env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY is not configured");const prompt=messages.map(m=>`${m.role==="assistant"?"ASSISTANT":"USER"}: ${m.content}`).join("\n\n");const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`;const r=await timeoutFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:`${SYSTEM_PROMPT}\n\nCONVERSATION:\n${prompt}`}]}],generationConfig:{maxOutputTokens:Math.min(maxTokens,65536)}})},50000);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error?.message||`Gemini HTTP ${r.status}`);const a=extractGeminiText(d);if(!a)throw new Error(`Gemini returned an empty response (${d?.candidates?.[0]?.finishReason||"UNKNOWN"})`);return a}
async function streamGroq(messages,env,maxTokens){if(!env.GROQ_API_KEY)throw new Error("GROQ_API_KEY is not configured");const r=await timeoutFetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.GROQ_API_KEY}`},body:JSON.stringify({model:GROQ_MODEL,messages:[{role:"system",content:SYSTEM_PROMPT},...messages],temperature:.3,max_tokens:Math.min(maxTokens,32768),stream:true})},50000);if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.error?.message||`Groq HTTP ${r.status}`)}const h=new Headers(CORS);h.set("Content-Type","text/event-stream; charset=utf-8");h.set("Cache-Control","no-cache, no-transform");h.set("Connection","keep-alive");return new Response(r.body,{status:200,headers:h})}
function wantsSearch(text){return /\b(latest|today|current|now|news|recent|price|weather|score|search|look up|web|2026|aaj|abhi|taza|khabar)\b/i.test(text||"")}
async function webSearch(query,env){if(!env.TAVILY_API_KEY)return "";try{const r=await timeoutFetch("https://api.tavily.com/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({api_key:env.TAVILY_API_KEY,query,search_depth:"basic",max_results:4})},8000);if(!r.ok)return "";const d=await r.json().catch(()=>null);return(d?.results||[]).map(x=>`Title: ${x.title||""}\nURL: ${x.url||""}\n${x.content||""}`).join("\n\n")}catch{return ""}}
async function supabaseRequest(env,path,options={},timeout=6000){if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)throw new Error("Supabase is not configured");return timeoutFetch(`${env.SUPABASE_URL}${path}`,{...options,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...(options.headers||{})}},timeout)}
async function loadHistory(id,env){if(!id||!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)return [];try{const r=await supabaseRequest(env,`/rest/v1/qasim_messages?conversation_id=eq.${encodeURIComponent(id)}&select=role,content&order=created_at.asc&limit=50`,{method:"GET"},5000);if(!r.ok)return [];const d=await r.json().catch(()=>[]);return Array.isArray(d)?normalizeMessages(d):[]}catch{return []}}
async function saveMessages(clientId,id,userText,answer,env){if(!clientId||!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)return id||null;try{if(!id){const r=await supabaseRequest(env,"/rest/v1/qasim_conversations?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({client_id:clientId,title:clean(userText).slice(0,80)||"New conversation"})},5000);const rows=await r.json().catch(()=>[]);id=rows?.[0]?.id||null}if(!id)return null;await Promise.all([supabaseRequest(env,"/rest/v1/qasim_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({conversation_id:id,role:"user",content:userText})},5000),supabaseRequest(env,"/rest/v1/qasim_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({conversation_id:id,role:"assistant",content:answer})},5000)]);return id}catch{return id||null}}
function dataUrl(v){const m=/^data:([^;]+);base64,(.+)$/s.exec(v||"");if(!m)return null;try{const b=atob(m[2]),bytes=new Uint8Array(b.length);for(let i=0;i<b.length;i++)bytes[i]=b.charCodeAt(i);return{mime:m[1],bytes}}catch{return null}}
function binaryToBase64(bytes){let b="";for(let i=0;i<bytes.length;i+=0x8000)b+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(b)}
async function fluxKleinImage(prompt,env,inputImages=[]){if(!env.AI)throw new Error("Workers AI binding AI is missing");const form=new FormData();form.append("prompt",`${prompt}\n\nPhotorealistic, natural lighting, realistic textures, accurate proportions, professional photography, crisp detail.`);form.append("width","1024");form.append("height","1024");for(let i=0;i<Math.min(inputImages.length,4);i++){const p=dataUrl(inputImages[i]);if(!p)continue;form.append(`input_image_${i}`,new File([p.bytes],`input-${i}.jpg`,{type:p.mime}))}const req=new Request("https://qasim-ai-multipart.invalid",{method:"POST",body:form});const result=await env.AI.run(FLUX_FAST_MODEL,{multipart:{body:req.body,contentType:req.headers.get("content-type")||"multipart/form-data"}});const image=typeof result?.image==="string"?result.image:typeof result?.response==="string"?result.response:"";if(!image)throw new Error("FLUX Klein returned no image");return{image,mime:"image/jpeg",provider:"Cloudflare FLUX.2 Klein 4B",model:FLUX_FAST_MODEL}}
async function fluxDevImage(prompt,env,inputImages=[]){if(!env.AI)throw new Error("Workers AI binding AI is missing");const form=new FormData();form.append("prompt",`${prompt}\n\nUltra-realistic, photorealistic, professional photography, natural lighting, realistic textures, realistic shadows, accurate proportions, cinematic composition.`);form.append("width","1024");form.append("height","1024");form.append("steps","16");for(let i=0;i<Math.min(inputImages.length,4);i++){const p=dataUrl(inputImages[i]);if(!p)continue;form.append(`input_image_${i}`,new File([p.bytes],`input-${i}.jpg`,{type:p.mime}))}const req=new Request("https://qasim-ai-multipart.invalid",{method:"POST",body:form});const result=await env.AI.run(FLUX_QUALITY_MODEL,{multipart:{body:req.body,contentType:req.headers.get("content-type")||"multipart/form-data"}});const image=typeof result?.image==="string"?result.image:typeof result?.response==="string"?result.response:"";if(!image)throw new Error("FLUX Dev returned no image");return{image,mime:"image/jpeg",provider:"Cloudflare FLUX.2 Dev",model:FLUX_QUALITY_MODEL}}
async function huggingFaceImage(prompt,env){if(!env.HF_TOKEN)throw new Error("HF_TOKEN is missing");const model="black-forest-labs/FLUX.1-schnell";const r=await timeoutFetch(`https://router.huggingface.co/hf-inference/models/${model}`,{method:"POST",headers:{Authorization:`Bearer ${env.HF_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({inputs:`${prompt}\nPhotorealistic professional photography, natural lighting.`})},45000);if(!r.ok)throw new Error(`Hugging Face HTTP ${r.status}`);return{image:binaryToBase64(new Uint8Array(await r.arrayBuffer())),mime:r.headers.get("content-type")||"image/jpeg",provider:"Hugging Face",model}}
async function falImage(prompt,env){if(!env.FAL_KEY)throw new Error("FAL_KEY is missing");const r=await timeoutFetch("https://fal.run/fal-ai/flux/schnell",{method:"POST",headers:{Authorization:`Key ${env.FAL_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({prompt,image_size:"square_hd",num_images:1})},45000);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail||d?.error||`fal.ai HTTP ${r.status}`);const u=d?.images?.[0]?.url;if(!u)throw new Error("fal.ai returned no image");const ir=await timeoutFetch(u,{},20000);return{image:binaryToBase64(new Uint8Array(await ir.arrayBuffer())),mime:ir.headers.get("content-type")||"image/jpeg",provider:"fal.ai",model:"fal-ai/flux/schnell"}}
async function replicateImage(prompt,env){if(!env.REPLICATE_API_TOKEN)throw new Error("REPLICATE_API_TOKEN is missing");const r=await timeoutFetch("https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions",{method:"POST",headers:{Authorization:`Bearer ${env.REPLICATE_API_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({input:{prompt}})},25000);let d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail||`Replicate HTTP ${r.status}`);for(let i=0;i<30;i++){if(d?.status==="succeeded")break;if(d?.status==="failed"||d?.status==="canceled")throw new Error(d?.error||"Replicate generation failed");await new Promise(x=>setTimeout(x,700));const p=await timeoutFetch(d.urls.get,{headers:{Authorization:`Bearer ${env.REPLICATE_API_TOKEN}`}},10000);d=await p.json().catch(()=>null)}const o=Array.isArray(d?.output)?d.output[0]:d?.output;if(!o)throw new Error("Replicate returned no image");const ir=await timeoutFetch(o,{},20000);return{image:binaryToBase64(new Uint8Array(await ir.arrayBuffer())),mime:ir.headers.get("content-type")||"image/jpeg",provider:"Replicate",model:"black-forest-labs/flux-schnell"}}
async function togetherImage(prompt,env){if(!env.TOGETHER_API_KEY)throw new Error("TOGETHER_API_KEY is missing");const r=await timeoutFetch("https://api.together.xyz/v1/images/generations",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.TOGETHER_API_KEY}`},body:JSON.stringify({model:"black-forest-labs/FLUX.1-schnell",prompt,width:1024,height:1024,steps:4,n:1,response_format:"b64_json"})},45000);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error?.message||`Together HTTP ${r.status}`);return{image:d?.data?.[0]?.b64_json,mime:"image/png",provider:"Together AI",model:"black-forest-labs/FLUX.1-schnell"}}
async function geminiImage(prompt,env){if(!env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY is missing");const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_IMAGE_MODEL}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`;const r=await timeoutFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:`${prompt}\nCreate a high-quality photorealistic image with natural lighting and realistic textures.`}]}],generationConfig:{responseModalities:["TEXT","IMAGE"]}})},45000);const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error?.message||`Gemini Image HTTP ${r.status}`);const part=(d?.candidates?.[0]?.content?.parts||[]).find(p=>p?.inlineData?.data||p?.inline_data?.data),inline=part?.inlineData||part?.inline_data;if(!inline?.data)throw new Error("Gemini Image returned no image");return{image:inline.data,mime:inline.mimeType||inline.mime_type||"image/png",provider:"Gemini Image",model:GEMINI_IMAGE_MODEL}}
async function generateImage(prompt,env,inputImages=[],quality="fast"){const providers=quality==="quality"?[{enabled:Boolean(env.AI),run:()=>fluxDevImage(prompt,env,inputImages)},{enabled:Boolean(env.GEMINI_API_KEY),run:()=>geminiImage(prompt,env)},{enabled:Boolean(env.FAL_KEY),run:()=>falImage(prompt,env)},{enabled:Boolean(env.HF_TOKEN),run:()=>huggingFaceImage(prompt,env)},{enabled:Boolean(env.REPLICATE_API_TOKEN),run:()=>replicateImage(prompt,env)},{enabled:Boolean(env.TOGETHER_API_KEY),run:()=>togetherImage(prompt,env)}]:[{enabled:Boolean(env.AI),run:()=>fluxKleinImage(prompt,env,inputImages)},{enabled:Boolean(env.GEMINI_API_KEY),run:()=>geminiImage(prompt,env)},{enabled:Boolean(env.HF_TOKEN),run:()=>huggingFaceImage(prompt,env)},{enabled:Boolean(env.FAL_KEY),run:()=>falImage(prompt,env)},{enabled:Boolean(env.TOGETHER_API_KEY),run:()=>togetherImage(prompt,env)},{enabled:Boolean(env.REPLICATE_API_TOKEN),run:()=>replicateImage(prompt,env)}];const errors=[];for(const p of providers){if(!p.enabled)continue;try{return await p.run()}catch(e){errors.push(e?.message||"unknown error")}}throw new Error(`All image providers failed. ${errors.join(" | ")}`)}
async function handleImage(request,env){const body=await readJSON(request);const prompt=clean(body?.prompt);if(!prompt)return json({error:{message:"Image prompt is required"}},400);const rawImages=Array.isArray(body?.images)?body.images:[];const inputImages=[...rawImages,...(body?.input_images||[]),...(body?.input_image?[body.input_image]:[])].filter(v=>typeof v==="string"&&v.startsWith("data:image/"));try{const result=await generateImage(prompt,env,inputImages,body?.quality==="quality"?"quality":"fast");return json({created:true,provider:result.provider,model:result.model||result.provider,data:[{b64_json:result.image,mime_type:result.mime}]})}catch(error){return json({error:{code:"ALL_IMAGE_PROVIDERS_FAILED",message:error?.message||"Image generation failed"}},502)}}
async function handleChat(request,env,ctx){const body=await readJSON(request);if(!Array.isArray(body?.messages))return json({error:{message:"messages array is required"}},400);let messages=normalizeMessages(body.messages);if(!messages.length)return json({error:{message:"No valid messages"}},400);const sessionId=clean(body?.session_id)||crypto.randomUUID(),clientId=clean(body?.client_id),maxTokens=clampInt(body?.max_output_tokens??body?.max_tokens,256,65536,16384);if(body?.load_history===true){const history=await loadHistory(sessionId,env);if(history.length)messages=[...history,...messages].slice(-20)}const lastUser=[...messages].reverse().find(m=>m.role==="user");if(!lastUser)return json({error:{message:"A user message is required"}},400);let searchContext="";if(body?.web_search===true&&wantsSearch(lastUser.content)){searchContext=await webSearch(lastUser.content,env);if(searchContext)messages=[...messages.slice(0,-1),{role:"user",content:`${lastUser.content}\n\nWEB SEARCH RESULTS:\n${searchContext}`}].slice(-20)}if(body?.stream===true){try{return await streamGroq(messages,env,maxTokens)}catch{}}let answer,provider,model,fallback=false;try{answer=await groq(messages,env,maxTokens);provider="Groq";model=GROQ_MODEL}catch(ge){try{answer=await gemini(messages,env,maxTokens);provider="Gemini";model=GEMINI_MODEL;fallback=true}catch(me){return json({error:{code:"AI_BACKENDS_UNAVAILABLE",message:`Groq failed: ${ge?.message||"unknown"}. Gemini failed: ${me?.message||"unknown"}.`}},503)}}if(!answer)return json({error:{code:"EMPTY_AI_RESPONSE",message:"AI returned an empty response. Please try again."}},503);ctx.waitUntil(saveMessages(clientId,sessionId,lastUser.content,answer,env));return json({id:`qasim-${crypto.randomUUID()}`,object:"chat.completion",provider,model,fallback,session_id:sessionId,choices:[{index:0,message:{role:"assistant",content:answer},finish_reason:"stop"}]})}
function health(env){return json({ok:true,service:"Qasim Mind API",chat_primary:GROQ_MODEL,chat_fallback:GEMINI_MODEL,image_fast_primary:FLUX_FAST_MODEL,image_quality_primary:FLUX_QUALITY_MODEL,workers_ai:Boolean(env.AI),database:Boolean(env.SUPABASE_URL&&env.SUPABASE_SERVICE_ROLE_KEY)})}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(request.method==="GET"&&(url.pathname==="/"||url.pathname==="/health"))return health(env);if(request.method==="POST"&&(url.pathname==="/v1/chat/completions"||url.pathname==="/chat/completions"))return handleChat(request,env,ctx);if(request.method==="POST"&&(url.pathname==="/v1/images/generations"||url.pathname==="/images/generations"))return handleImage(request,env);return json({error:{message:"Endpoint not found"}},404)}};