const ALLOWED_ORIGIN="https://q9999499-collab.github.io";
const GEMINI_MODEL="gemini-3.6-flash";
const FALLBACK_MODEL="llama-3.3-70b-versatile";
const IMAGE_MODEL="@cf/black-forest-labs/flux-2-dev";
const SYSTEM_PROMPT=`You are Qasim AI. Understand English, Urdu, Roman Urdu and mixed language. Give accurate, useful, complete answers. Never invent facts or claim a tool was used when it was not. Use supplied web/file context when available.`;
const CORS={"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,X-Qasim-Client","Access-Control-Max-Age":"86400","Vary":"Origin"};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json;charset=utf-8",...CORS}});
const clean=v=>typeof v==="string"?v.replace(/\u0000/g,"").trim():"";
async function body(r){try{return await r.json()}catch{return null}}
function wantsSearch(text){return /\b(latest|today|current|now|news|recent|search|look up|web|2026|aaj|abhi|taza|khabar)\b/i.test(text||"")}
async function webSearch(q,env){if(!env.TAVILY_API_KEY)return"";try{const r=await fetch("https://api.tavily.com/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({api_key:env.TAVILY_API_KEY,query:q,max_results:5,search_depth:"basic"})});if(!r.ok)return"";const d=await r.json();return(d.results||[]).map(x=>`Title: ${x.title}\nURL: ${x.url}\nContent: ${x.content}`).join("\n\n")}catch{return""}}
function geminiParts(messages,files,search){const p=[];for(const m of messages)p.push({text:`${m.role.toUpperCase()}: ${m.content}`});if(search)p.push({text:`WEB SEARCH RESULTS:\n${search}`});for(const f of(files||[]).slice(0,6)){if(f.data&&f.mime_type?.startsWith("image/"))p.push({inline_data:{mime_type:f.mime_type,data:f.data}});else if(f.text)p.push({text:`FILE ${f.name||"document"}:\n${f.text}`})}return p}
async function gemini(messages,files,search,env){if(!env.GEMINI_API_KEY)throw Error("GEMINI_API_KEY is not configured");const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:SYSTEM_PROMPT},...geminiParts(messages,files,search)]}],generationConfig:{temperature:.2,maxOutputTokens:4096}})});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.error?.message||`Gemini error ${r.status}`);const text=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("").trim();if(!text)throw Error("Gemini returned an empty response");return text}
async function groq(messages,env){if(!env.GROQ_API_KEY)throw Error("GROQ_API_KEY is not configured");const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.GROQ_API_KEY}`},body:JSON.stringify({model:FALLBACK_MODEL,messages:[{role:"system",content:SYSTEM_PROMPT},...messages.slice(-16)],temperature:.2,max_tokens:4096})});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.error?.message||`Fallback error ${r.status}`);return clean(d?.choices?.[0]?.message?.content)}
async function sb(env,path,opt){return fetch(env.SUPABASE_URL+path,{...opt,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...(opt.headers||{})}})}
async function saveMessages(clientId,conversationId,messages,env){if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY||!clientId)return conversationId||null;try{let id=conversationId;if(!id){const r=await sb(env,"/rest/v1/qasim_conversations?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({client_id:clientId,title:(messages.find(x=>x.role==="user")?.content||"New conversation").slice(0,80)})});id=(await r.json())[0]?.id}for(const m of messages.slice(-2))await sb(env,"/rest/v1/qasim_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({conversation_id:id,role:m.role,content:m.content})});return id}catch(e){console.error("history",e);return conversationId||null}}
async function chat(req,env){const b=await body(req);if(!Array.isArray(b?.messages)||!b.messages.length)return json({error:{message:"messages required"}},400);const messages=b.messages.filter(x=>x&&["user","assistant"].includes(x.role)&&typeof x.content==="string").slice(-16);const last=messages.at(-1)?.content||"";const search=b.web_search!==false&&wantsSearch(last)?await webSearch(last,env):"";let answer,provider="gemini";try{answer=await gemini(messages,b.files,search,env)}catch(e){console.error("Gemini",e);try{answer=await groq(messages,env);provider="fallback"}catch(f){console.error("fallback",f);return json({error:{code:"AI_BACKENDS_UNAVAILABLE",message:"Gemini and fallback AI are unavailable. Check GEMINI_API_KEY/GROQ_API_KEY and the Gemini model configuration in Cloudflare Worker Secrets."}},503)}}const cid=await saveMessages(b.client_id,b.conversation_id,[...messages,{role:"assistant",content:answer}],env);return json({id:`qasim-${crypto.randomUUID()}`,object:"chat.completion",provider,web_search:Boolean(search),conversation_id:cid,choices:[{index:0,message:{role:"assistant",content:answer},finish_reason:"stop"}]})}
function dataUrl(s){const m=/^data:([^;]+);base64,(.+)$/s.exec(s||"");if(!m)return null;const bin=atob(m[2]),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return{mime:m[1],bytes:a}}
async function image(req,env){const b=await body(req),prompt=clean(b?.prompt);if(!prompt)return json({error:{message:"Image prompt required"}},400);if(!env.AI)return json({error:{message:"Cloudflare AI binding missing"}},500);try{const f=new FormData();f.append("prompt",`${prompt}\nPhotorealistic professional photography, natural lighting, realistic textures, accurate proportions, realistic shadows, crisp fine detail, cinematic but natural color grading, no artificial look.`);f.append("width",String(Math.min(1920,Math.max(256,Number(b.width)||1024))));f.append("height",String(Math.min(1920,Math.max(256,Number(b.height)||1024))));if(b.input_image){const p=dataUrl(b.input_image);if(!p)return json({error:{message:"Invalid input image"}},400);f.append("input_image_0",new File([p.bytes],"reference.jpg",{type:p.mime}))}const fr=new Response(f);const r=await env.AI.run(IMAGE_MODEL,{multipart:{body:fr.body,contentType:fr.headers.get("content-type")}});const img=typeof r?.image==="string"?r.image:typeof r?.response==="string"?r.response:"";if(!img)throw Error("Image backend returned no image");return json({model:IMAGE_MODEL,data:[{b64_json:img,mime_type:"image/jpeg"}]})}catch(e){return json({error:{code:"IMAGE_ERROR",message:e?.message||"Image generation failed"}},502)}}
async function history(req,env){const b=await body(req);if(!b?.client_id)return json({error:{message:"client_id required"}},400);if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)return json({conversations:[],configured:false});const r=await sb(env,`/rest/v1/qasim_conversations?client_id=eq.${encodeURIComponent(b.client_id)}&select=*&order=updated_at.desc`,{method:"GET"});return json({conversations:await r.json(),configured:true})}
export default{async fetch(req,env){const u=new URL(req.url),o=req.headers.get("Origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(o&&o!==ALLOWED_ORIGIN)return json({error:{message:"Origin not allowed"}},403);if(req.method==="GET"&&(u.pathname==="/"||u.pathname==="/health"))return json({ok:true,service:"Qasim AI API",chat_provider:"Gemini",gemini_model:GEMINI_MODEL,fallback:FALLBACK_MODEL,image_model:IMAGE_MODEL,web_search:true,files:true,database:Boolean(env.SUPABASE_URL),website_limits:"none"});if(req.method!=="POST")return json({error:{message:"Use POST"}},405);if(u.pathname==="/v1/chat/completions"||u.pathname==="/chat/completions")return chat(req,env);if(u.pathname==="/v1/images/generations"||u.pathname==="/images/generations")return image(req,env);if(u.pathname==="/v1/history")return history(req,env);return json({error:{message:"Endpoint not found"}},404)}};