const ALLOWED_ORIGIN = "https://q9999499-collab.github.io";
const CHAT_MODEL = "@cf/zai-org/glm-4.7-flash";
const IMAGE_MODEL = "@cf/black-forest-labs/flux-2-dev";
const MAX_MESSAGE_CHARS = 12000;
const MAX_CONTEXT_MESSAGES = 16;
const MAX_COMPLETION_TOKENS = 4096;
const SYSTEM_PROMPT = `You are Qasim AI, a careful, capable multilingual assistant. Understand English, Urdu, Roman Urdu, and mixed Urdu/English. Reply naturally in the user's language. Answer the exact question asked. Never invent facts, citations, searches, tools, actions, files, or results. For math and science, reason carefully and verify conclusions.`;
const CORS = {"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Vary":"Origin"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...CORS}})}
function clean(v){return typeof v==="string"?v.replace(/\u0000/g,"").trim():""}
async function readJSON(r){try{return await r.json()}catch{return null}}
function extractText(r){if(typeof r==="string")return clean(r);if(!r||typeof r!=="object")return"";for(const v of[r.response,r.text,r.output_text,r.answer,r.generated_text,r.content,r.message?.content,r.choices?.[0]?.message?.content,r.choices?.[0]?.text]){const t=clean(v);if(t)return t}return""}
function recentMessages(ms){return ms.filter(m=>m&&["user","assistant"].includes(m.role)&&typeof m.content==="string").slice(-MAX_CONTEXT_MESSAGES)}
function quotaError(e){const s=String(e?.message||e||"");return /4006|daily free allocation|10,000 neurons|daily.*allocation/i.test(s)}
async function chat(request,env){const b=await readJSON(request);if(!Array.isArray(b?.messages)||!b.messages.length)return json({error:{message:"A non-empty messages array is required."}},400);const messages=[];for(const m of b.messages){if(!m||!["user","assistant","system"].includes(m.role)||typeof m.content!=="string")return json({error:{message:"Invalid message format."}},400);const c=clean(m.content);if(!c)continue;if(c.length>MAX_MESSAGE_CHARS)return json({error:{message:"Message is too long."}},400);if(m.role!=="system")messages.push({role:m.role,content:c})}try{const r=await env.AI.run(CHAT_MODEL,{messages:[{role:"system",content:SYSTEM_PROMPT},...recentMessages(messages)],max_completion_tokens:MAX_COMPLETION_TOKENS,temperature:.15,top_p:.9});const text=extractText(r);if(!text)return json({error:{message:"The AI model returned an empty response. Please try again."}},502);return json({id:`qasim-${crypto.randomUUID()}`,object:"chat.completion",created:Math.floor(Date.now()/1000),model:CHAT_MODEL,choices:[{index:0,message:{role:"assistant",content:text},finish_reason:"stop"}]})}catch(e){console.error("chat",e?.stack||e);if(quotaError(e))return json({error:{code:"AI_QUOTA_EXHAUSTED",message:"Cloudflare Workers AI daily free quota is exhausted. No retry was made because retrying cannot bypass the quota."}},429);return json({error:{message:e?.message||"Cloudflare Workers AI request failed."}},502)}}
function dataUrlToBytes(s){const m=/^data:([^;]+);base64,(.+)$/s.exec(s||"");if(!m)return null;const bin=atob(m[2]),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return{mime:m[1],bytes}}
function imageFromResult(r){if(!r)return"";if(typeof r==="string")return r;if(typeof r.image==="string")return r.image;if(typeof r.response==="string")return r.response;if(typeof r.output==="string")return r.output;return""}
async function generateImage(request,env){const b=await readJSON(request),prompt=clean(b?.prompt);if(!prompt)return json({error:{message:"Image prompt is required."}},400);if(prompt.length>4000)return json({error:{message:"Image prompt is too long."}},400);try{const form=new FormData();form.append("prompt",prompt);form.append("width",String(Math.min(1920,Math.max(256,Number(b?.width)||1024))));form.append("height",String(Math.min(1920,Math.max(256,Number(b?.height)||1024))));if(b?.guidance!=null)form.append("guidance",String(b.guidance));if(b?.seed!=null)form.append("seed",String(b.seed));if(b?.input_image){const p=dataUrlToBytes(b.input_image);if(!p)return json({error:{message:"Invalid input image."}},400);if(p.bytes.byteLength>4*1024*1024)return json({error:{message:"Input image is too large. Maximum is 4 MB."}},400);form.append("input_image_0",new File([p.bytes],"reference.jpg",{type:p.mime||"image/jpeg"}))}const fr=new Response(form);const r=await env.AI.run(IMAGE_MODEL,{multipart:{body:fr.body,contentType:fr.headers.get("content-type")}});const image=imageFromResult(r);if(!image)return json({error:{message:"Image model returned no image. Check Workers AI model availability."}},502);return json({created:Math.floor(Date.now()/1000),model:IMAGE_MODEL,data:[{b64_json:image,mime_type:"image/jpeg"}]})}catch(e){console.error("image",e?.stack||e);if(quotaError(e))return json({error:{code:"AI_QUOTA_EXHAUSTED",message:"Cloudflare Workers AI daily free quota is exhausted. Image generation is temporarily unavailable until the quota resets or the plan is upgraded. No retry was made."}},429);return json({error:{message:e?.message||"Cloudflare image generation/editing failed."}},502)}}
export default{async fetch(request,env){const url=new URL(request.url),origin=request.headers.get("Origin");if(request.method==="OPTIONS"){if(origin&&origin!==ALLOWED_ORIGIN)return json({error:{message:"Origin not allowed."}},403);return new Response(null,{status:204,headers:CORS})}if(origin&&origin!==ALLOWED_ORIGIN)return json({error:{message:"Origin not allowed."}},403);if(request.method==="GET"&&(url.pathname==="/"||url.pathname==="/health"))return json({ok:true,service:"Qasim AI API",status:"online",provider:"Cloudflare Workers AI",model:CHAT_MODEL,image_model:IMAGE_MODEL,image_generation:true,image_editing:true,website_limits:"none"});if(!env.AI||typeof env.AI.run!=="function")return json({error:{message:"Cloudflare Workers AI binding named AI is missing."}},500);if(request.method!=="POST")return json({error:{message:"Use POST for this endpoint."}},405);if(url.pathname==="/v1/chat/completions"||url.pathname==="/chat/completions")return chat(request,env);if(url.pathname==="/v1/images/generations"||url.pathname==="/images/generations")return generateImage(request,env);return json({error:{message:"Endpoint not found."}},404)}};
